services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-waves-visualizer
    network_mode: host
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_DEVELOPER_MODE=true
    restart: unless-stopped

